BF-FrontEnd-class/agile-development-group2-hyf-rebuild

.cspell.json, README.md
=> project definiton added

planning/constraints.md
=> add constraints md

.cspell.json, package.json, planning/communication.md
=> Add communication plan

.cspell.json, pages/digitalents.html, pages/program.html, pages/volunteer.html, planning/user-personas.md, styles/digitalents.css, styles/program.css, styles/volunteer.css
=> User personas

planning/backlog.md
=> add backlog for digitalents page

index.html, pages/digitalents.html, pages/program.html, pages/volunteer.html, styles/index.css
=> add footer

index.html, pages/digitalents.html, pages/volunteer.html
=> added footer to all pages

index.html
=> fixed minor css links

.cspell.json, index.html, styles/index.css
=> Add navigation bar

index.html, pages/digitalents.html, pages/program.html, pages/volunteer.html, planning/backlog.md, styles/index.css
=> fixed the logo position

index.html, pages/digitalents.html, pages/program.html, pages/volunteer.html, styles/index.css
=> minor logo fixes

pages/digitalents.html, pages/program.html, pages/volunteer.html
=> footer added to all pages

pages/program.html, styles/program.css
=> title of the program page added

pages/volunteer.html, styles/volunteer.css
=> description part added

pages/volunteer.html, styles/volunteer.css
=> buttons: mentor, coach added

pages/digitalents.html, styles/digitalents.css, styles/index.css
=> added digitalents page description

pages/program.html, styles/program.css
=> Upcoming trainings button added

pages/digitalents.html, styles/digitalents.css
=> add program offers title to digitalents page

pages/program.html, styles/program.css
=> margins added to the buttons

index.html, main.js, styles/home.css
=> Added support developers to home

pages/digitalents.html, styles/digitalents.css
=> add asap.net program  to digitalent

main.js, pages/program.html
=> title animation added

main.js, pages/program.html
=> script tag modified

index.html, styles/home.css
=> Home map fix

index.html, styles/home.css
=> Minor fixes home

pages/digitalents.html, styles/digitalents.css
=> add who can apply description title

pages/digitalents.html, styles/digitalents.css
=> add who can apply descriptive text

pages/digitalents.html, styles/digitalents.css
=> add who can apply button

styles/program.css
=> mobile responsiveness added

styles/program.css
=> minor responsive issues fixed

main.js, styles/program.css
=> css animation added

.cspell.json, index.html, styles/home.css
=> Home responsive design

main.js, styles/index.css
=> Logo responsiveness added

styles/digitalents.css
=> update digitalent page responsiveness

styles/index.css
=> removed CSS unnecesary link

pages/volunteer.html, styles/index.css, styles/volunteer.css
=> add  media queries

styles/digitalents.css
=> add animation to digitalent page

styles/digitalents.css
=> fixing digitalents animation 

planning/retrospective.md
=> Retrospective
